### ISSUE TITLE
Handling UFF58 files in OpenModal

### ISSUE THREAD

**Issue by JonathanArandaEC** [ladisk/pyuff#30]
Hi, I'am a student of mechanical engineering. Congratulations for the project. If you load only accelerance data, how does OpenModal obtain the FRF in units of Newtons ((m/s2)/N)?
Thanks.

**Comment by jankoslavic** [comment]
Hi @JonathanArandaEC! This are issues about pyUFF:) The units should be properly handled if you use OM also for measurements, if you are importing data via uff, then you relly on uff data structure. Hope this helps.

**Comment by JonathanArandaEC** [comment]
> Hi @JonathanArandaEC! This are issues about pyUFF:) The units should be properly handled if you use OM also for measurements, if you are importing data via uff, then you relly on uff data structure. Hope this helps.

Hi! I am working on a project, and I am importing  accelerance data via UFF (I can't measure the input force), with the purpose of obtain the modes shapes of a beam. However, OpenModal Shows the FRF with units of Newtons.

Thanks for your time an help!
