### ISSUE TITLE
ValueError: could not convert string to float

### ISSUE THREAD

**Issue by ziadrida** [ladisk/pyuff#31]
I get "ValueError: could not convert string to float: '000E+00  5.460279062'"
  1377                             [float(line[13 * (i + j) + 20 * (i):13 * (i + 1) + 20 * (i + j)]) \
-> 1378                              for i in range(len(line) // 33) for j in [0, 1]])

Error is in this block of the UFF file

v2;38868
RML-03M4071-20170104-CYC-00003
20-07-24T07:23:45Z
38868-VE003
NacXdir.ISOA-21[0.1-10];m/s2
    0         0    0         0 Channel_11         0   0 NONE               0   0
         4         1         0  0.00000E+00  0.00000E+00  0.00000E+00
        17    0    0    0 Time                 s                   
         1    0    0    0 NacXdir.ISOA-21[0.1- m/s2                
         0    0    0    0 NONE                 NONE                
         0    0    0    0 NONE                 NONE                
  0.000000000000E+00  5.460279062390E-02

It seems not the know how to parse line 13. 

Block of code:

                elif (dset['ord_data_type'] == 4) and (dset['abscissa_spacing'] == 0):
                    for line in split_data:  # 2(E13.5,E20.12)
                        values.extend(
                            [float(line[13 * (i + j) + 20 * (i):13 * (i + 1) + 20 * (i + j)]) \
                             for i in range(len(line) // 33) for j in [0, 1]])

I am still investigating but thought someone may already know what is going on here.

**Comment by jankoslavic** [comment]
Dear @ziadrida ! I have not checked the details, but it looks like your file is not up to specifications. Length specification is: E13.5,E20.12) while your data looks to be 2x19 characters long

**Comment by ziadrida** [comment]
thanks for the quick respose.
[Archive.zip](https://github.com/openmodal/pyuff/files/5841987/Archive.zip)

Here is a file that will fail. If I change the abscissa_spacing value from 0 to 1 it will work.
t1.uff fails
t2.uff works

**Comment by ziadrida** [comment]
If I understand you response, when the abscissa_spacing is 0, the columns should be (E13.5, E20.12). 
Which case is this in here https://svibs.com/uff-data-set-number-58/ ?

**Comment by ziadrida** [comment]
@jankoslavic, was there a change to the specification such that if we use an older version we can read the files? These files are being generated by CMS sensors, so it would be hard for us to modify them. best regards.

**Comment by jankoslavic** [comment]
The data should match the header; here it does not. The specifications did not change for 30+ years :D. However, prior to approx 2 years ago pyuff, separated values by spaces (as this was wrong and not according to specifications, we have changed it)
