### ISSUE TITLE
Dataset 2414 handling

### ISSUE THREAD

**Issue by kdegrendele** [ladisk/pyuff#37]
Hi, I need to integrate DS2414 (write and read).
So I plan to do it on my fork. I will make a pull request ASAP.

**Comment by jankoslavic** [comment]
Great @kdegrendele you are welcome and can count on my support!

**Comment by nilswagner** [comment]
This is a very useful extension.

**Comment by jankoslavic** [comment]
We have a pull request in progress: https://github.com/openmodal/pyuff/pull/39 
There is just one issue which needs to be resolved. Hopefully soon. Help would be appreciated.

**Comment by jankoslavic** [comment]
Thank you @kdegrendele this is a great PR!!!
