### ISSUE TITLE
BUG: extract for dataset 2411 is same as for 15

### ISSUE THREAD

**Issue by klemengit** [ladisk/pyuff#43]
Method ``_extract2411`` is the same as for the ``_extract15``:
https://github.com/ladisk/pyuff/blob/db1faf11e92021cc4b7b354badfb7cbb158e4fd2/pyuff.py#L1183

Method for reading dataset 2411 currently doesn't exist.

**Comment by jankoslavic** [comment]
we are also missing test data.

**Comment by nilswagner** [comment]
Test data for dataset 2411 and 2414
[tulay_01.unv.gz](https://github.com/ladisk/pyuff/files/6799407/tulay_01.unv.gz)

**Comment by jankoslavic** [comment]
@nilswagner thank you for the file. I have uploaded the file. We need help in implementing the extraction 4211.

**Comment by jankoslavic** [comment]
This issue can be closed; both datatypes and tests are implemented!
