### ISSUE TITLE
uff_file.get_set_types() returns float values

### ISSUE THREAD

**Issue by nilswagner** [ladisk/pyuff#46]
IMHO, 

`uff_file = pyuff.UFF(uff)
print (uff_file.get_set_types())`

should return integer values and not floats

`[  15. 2412.   55.   55.   55.   55.   55.   55.   55.   55.   55.   55.
   55.   55.   55.   55.]
`

**Comment by jankoslavic** [comment]
Agree! :) Volunteer required.

**Comment by nilswagner** [comment]
#47

**Comment by jankoslavic** [comment]
Thanks @nilswagner
