### ISSUE TITLE
(UFF58 file)ValueError: could not convert string to float: '000E+00  0.000000000'

### ISSUE THREAD

**Issue by Sunshinera** [ladisk/pyuff#52]
Hi,
When I use the statements like:
_data = uff_file.read_sets()
data.items()
print(data.items())_

I have got the error as:
 _File ".site-packages\pyuff.py", line 1562, in _extract58
    [float(line[13 * (i + j) + 20 * (i):13 * (i + 1) + 20 * (i + j)]) \
  File ".site-packages\pyuff.py", line 1562, in <listcomp>
    [float(line[13 * (i + j) + 20 * (i):13 * (i + 1) + 20 * (i + j)]) \
ValueError: could not convert string to float: '000E+00  0.000000000'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File ".site-packages\pyuff.pypyuff.py", line 441, in read_sets
    dset.append(self._read_set(ii))
  File "site-packages\pyuff.py", line 545, in _read_set
    dset = self._extract58(blockData)
  File ".site-packages\pyuff.py", line 1600, in _extract58
    raise UFFException('Error reading data-set #58b')
pyuff.UFFException: Error reading data-set #58b_

![image](https://user-images.githubusercontent.com/87689778/126272647-2e5c5fc7-d446-4831-8d1c-f5d14d804150.png)

![image](https://user-images.githubusercontent.com/87689778/126272911-7b157f1a-e9bc-4a3a-9379-62646ce79f5d.png)

And the uff files shows like this
_-1
58
v2;227935
RML-03M4071-20200401-CYC-00003
21-06-03T03:21:06Z
227935-WTG01
NacDirAct;deg
0         0    0           0 AP                 0   0 NONE               0   0
4         1         0    0.00000E+00  0.00000E+00  0.00000E+00
17    0    0      0 Time                 s
1    0    0      0 NacDirAct            deg
0    0    0      0 NONE                 NONE
0    0    0      0 NONE                 NONE
0.000000000000E+00    1.848999938965E+02_

And I don't know what I should do next. 
Pls give me a hand!
Thank you very much.

**Comment by jankoslavic** [comment]
The data does not look ok. With regard to the header there should be uneven data (double precision)
real      double       uneven     2(E13.5,E20.12)

Does this help you?

**Comment by Sunshinera** [comment]
Thanks a lot!
