### ISSUE TITLE
object has no attribute '_refresh'

### ISSUE THREAD

**Issue by ziadrida** [ladisk/pyuff#56]
method in this block calls _refresh() which does not exist

     if not self._refreshed:
            if not self._refresh():
                raise Exception('Cannot read from the file: ' + self._filename)

**Comment by klemengit** [comment]
It seems that with the restructuring of the package a this method name remained unchanged (now it should be `self.refresh()`). I'll make sure that that's the case and make a PR.

**Comment by jankoslavic** [comment]
just a reminder on this open issue

**Comment by jankoslavic** [comment]
Thanks @klemengit
