### ISSUE TITLE
New feature to handle time data with DS2414

### ISSUE THREAD

**Issue by kdegrendele** [ladisk/pyuff#62]
Hello, I have created a fork on which I plan to add an analysis_type of 4 (and not only 5) to handle time signals.
Thank you

**Comment by jankoslavic** [comment]
Thanks for the update; looking forward to see the implementation. If you will need help with pr, you can count on me.

**Comment by theScriptingEngineer** [comment]
Hello @kdegrendele,
I have implemented a more general support for dataset 2414. I supports dataset_location 1/2/3.
I have kept the special treatment of _analysis_type==5_ in order not to break the existing code.

you can find it on: [FEASupport branch](https://github.com/theScriptingEngineer/pyuff/tree/FEASupport)

Regards,
Frederik

**Comment by jankoslavic** [comment]
The PR by Frederik is now in v2.1. Thanks.

**Comment by jankoslavic** [comment]
@kdegrendele , @theScriptingEngineer , can we close this issue

**Comment by theScriptingEngineer** [comment]
from my side, no problem.
