### ISSUE TITLE
Wheels for 2.4.1 does not contain code

### ISSUE THREAD

**Issue by hakostra** [ladisk/pyuff#86]
There is a serious problem with the published wheels for the 2.4.1 release on pypi, they do not contain any code!!!

`pip install pyuff==2.4.1` and then running python:

```
Python 3.10.12 (main, Nov 20 2023, 15:14:05) [GCC 11.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import pyuff
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'pyuff'
>>>
```

I downloaded the wheel from [pypi.org](https://pypi.org/project/pyuff/2.4.1/#files) and it does not contain any code at all, not a single Python file is in there, so no winder why it does not work.

I would recommend **yanking** the release from pypi **ASAP**, because this breaks lots of things, and then **afterwards**, publish a valid 2.4.2 as soon as the issue is identified and fixed.

**Comment by hakostra** [comment]
Thanks. I need to `pip cache purge` before I try to `pip install pyuff` - this now gives the old 2.4 version which will work just fine.

Yanking the non-working one was the urgent part, fixing this has no immediate hurry.

As the problem is solved from my side, you might just close this issue if you like. If you like to keep it open as a reminder to find out what went wrong, that's also fine. I don't close it now, but feel free to close it if you like.

**Comment by jankoslavic** [comment]
Thanks. I will keep it open, just in case anyone else has the same problem. We will close it once we resolve the issue and have proper build. Have a nice weekend!

**Comment by klemengit** [comment]
Dear @hakostra , we have made another release (2.4.2) on [pypi](https://pypi.org/project/pyuff/).

When you are able, can you please confirm that everything is working with the new version? We have tested it on our side and it should work now.

Thank you for promptly reporting the issue!

**Comment by hakostra** [comment]
Everything seems to work now. Thanks for solving the issue promptly!
