### ISSUE TITLE
feature request: read_sets() without loading data

### ISSUE THREAD

**Issue by jlmoreno93** [ladisk/pyuff#94]
Hi pyuff developers,

First off, thank you for your fantastic work on this library and your contributions to the structural dynamics community!

Regarding the read_sets() function: Would it be possible to add an option to read only the metadata without loading the actual data (data and x)?

This would be helpful for reducing computation time when just browsing dataset channels in large UFF files (1GB+), where read_data() can take 25+ seconds to execute. It could also enable a more lazy loading approach when implementing in applications.

I experimented with this on dataset 58, and by adding this functionality to read in just metadata, the processing time was reduced to a couple of seconds.

Is this something that could be considered for a future update? I would be happy to contribute.

**Comment by jankoslavic** [comment]
@jlmoreno93 this is a great suggestion. Can you try to prepare a pull request?

**Comment by jlmoreno93** [comment]
Definitely, I will try to come up with something presentable.

**Comment by jankoslavic** [comment]
This issue is resolved with PR: https://github.com/ladisk/pyuff/pull/95
